spring.application.name=FraudDetect
server.port=8081

spring.ai.openai.api-key=${OPEN_AI_API}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=openai/gpt-oss-120b
google.safe-browsing.api-key=${GOOGLE_SAFE_API}

